# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_dnsconfig_right_subnet_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dnsconfig',
        ),
    ]
